import { IEntity } from "../../models/entity.model";

export interface IGwuColumn {
    column: number;
    entities: IEntity[];
    image: string;
  }

export const columns: IGwuColumn[] = [
    {
        column: 1,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'WHFA-196',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            }
        ],
        image: ''
    },
    {
        column: 2,
        entities: [
            
        ],
        image: '../../../assets/wave-lines/001.png'
    },
    {
        column: 3,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B3',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B4',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B42',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B43',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
        ],
        image: ''
    },
    {
        column: 4,
        entities: [
            
        ],
        image: '../../../assets/wave-lines/002.png'
    },
    {
        column: 5,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'PBYJ-873',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'AMYU-897',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'LQBY-17',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'FKKR-176',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'AGSC-053',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'FERO-700',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            }
        ],
        image: ''
    },
    {
        column: 6,
        entities: [
            
        ],
        image: '../../../assets/wave-lines/003.png'
    },
    {
        column: 7,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'OGA-546',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'ADTC-116',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            }
        ],
        image: ''
    },
    {
        column: 8,
        entities: [
            
        ],
        image: '../../../assets/wave-lines/004.png'
    },
    {
        column: 9,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B9',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B11',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            }
        ],
        image: ''
    },
    {
        column: 10,
        entities: [
            
        ],
        image: '../../../assets/wave-lines/005.png'
    },
    {
        column: 11,
        entities: [
            {
                category: 'Part',
                id: 1,
                name: 'QDUF-602',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'VALO-460',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'QKQ-58',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
            {
                category: 'Part',
                id: 1,
                name: 'EXH-SU-B1342',
                description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                date: '',
                active: false,
                selected: false,
                disabled: false,
                formattedDate: '',
                showDetails: false,
                tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
                progress: 0,
                walletFavorite: false,
                walletDate: '',
                formattedWalletDate: '',
                launchbar: false,
                details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            },
        ],
        image: ''
    }
    // {
    //     column: 12,
    //     entities: [
            
    //     ],
    //     image: '../../../assets/gwulines.png'
    // }
]