import { IEntity } from "../../models/entity.model";

export const sourceDocumentSamples: IEntity[] = [
    {
        category: 'Part',
        id: 1,
        name: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum', 'Lorem Ipsum', 'Sit Amet', 'Lorem', 'Lorem, Dolor, and 3 more'],
        progress: 0,
        walletFavorite: false,
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        category: 'Part',
        id: 2,
        name: 'EXH-SU-5110-C',
        description: 'Lorem upsum door sit amet consectetur',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 0,
        walletFavorite: false,
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    },
    {
        category: 'Part',
        id: 3,
        name: 'EXH-SU-5110-D',
        description: 'Lorem upsum door sit amet consectetur',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 0,
        walletFavorite: false,
        details: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    }
];
