export const targetDocumentSamples = [
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 100,
    },
    {
        title: 'EXH-SU-5110-C',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 86,
    },
    {
        title: 'EXH-SU-5110-D',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 80,
    },
    {
        title: 'EXH-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 76,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 76,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 75,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 54,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 53,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 50,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 48,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 40,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 35,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 35,
    },
    {
        title: 'EXH-SU-5110-B',
        description: 'Lorem upsum door sit amet consectetur',
        active: false,
        tags: ['Lorem Ipsum', 'Sit amet', 'Lorem, Dolor, and 3 more', 'Lorem', 'Ipsum'],
        progress: 11,
    }
]
