import { IFileFolder } from "../models/file-folder.model";

export const presetFiles: IFileFolder = {
    name: "all",
    type: "folder",
    folders: [
        {
            name: "Engineering Drawings",
            type: "folder",
            folders: [

            ],
            files: [
                {
                    category: 'Part',
                    type: 'file',
                    id: 1,
                    name: 'ED-759385 Bracket Assembly',
                    description: 'Description about the item.',
                    date: '',
                    active: false,
                    selected: false,
                    disabled: false,
                    formattedDate: '',
                    showDetails: false,
                    tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
                    progress: 0,
                    walletFavorite: false,
                    details: 'More details about the item.',
                    walletDate: new Date().toString(),
                    formattedWalletDate: '',
                    launchbar: false,
                    menuActive: false
                }
            ],
            open: false,
            shared: false,
            menuOpen: false,
            file: null,
            menuActive: false
        },
        {
            name: "Regulatory Requirements",
            type: "folder",
            folders: [
                // {
                //     name: "DOE",
                //     type: "folder",
                //     folders: [],
                //     files: [],
                //     open: false,
                //     shared: false,
                //     menuOpen: false,
                //     file: null,
                //     menuActive: false
                // },
                // {
                //     name: "DOT",
                //     type: "folder",
                //     folders: [],
                //     files: [],
                //     open: false,
                //     shared: false,
                //     menuOpen: false,
                //     file: null,
                //     menuActive: false
                // },
                // {
                //     name: "NTSB",
                //     type: "folder",
                //     folders: [],
                //     files: [],
                //     open: false,
                //     shared: false,
                //     menuOpen: false,
                //     file: null,
                //     menuActive: false
                // }
            ],
            files: [
                {
                    category: 'Part',
                    type: 'file',
                    id: 1,
                    name: 'SDS-XLR17 Lubricant',
                    description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                    date: '',
                    active: false,
                    selected: false,
                    disabled: false,
                    formattedDate: '',
                    showDetails: false,
                    tags: ['SDS', 'Lubricant', 'Polymer', 'Chemical', 'Meterial', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
                    progress: 0,
                    walletFavorite: false,
                    walletDate: '',
                    formattedWalletDate: '',
                    launchbar: false,
                    menuActive: false,
                    details: 'More details about the item.',
        
                },
                {
                    category: 'Part',
                    type: 'file',
                    id: 1,
                    name: 'SDS Chromium',
                    description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                    date: '',
                    active: false,
                    selected: false,
                    disabled: false,
                    formattedDate: '',
                    showDetails: false,
                    tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
                    progress: 0,
                    walletFavorite: false,
                    walletDate: '',
                    formattedWalletDate: '',
                    launchbar: false,
                    menuActive: false,
                    details: 'More details about the item.',
        
                },
                {
                    category: 'Part',
                    type: 'file',
                    id: 1,
                    name: 'SDS Pennzoil Full Synthetic Motor Oil',
                    description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                    date: '',
                    active: false,
                    selected: false,
                    disabled: false,
                    formattedDate: '',
                    showDetails: false,
                    tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
                    progress: 0,
                    walletFavorite: false,
                    walletDate: '',
                    formattedWalletDate: '',
                    launchbar: false,
                    menuActive: false,
                    details: 'More details about the item.',
        
                },
                {
                    category: 'Part',
                    type: 'file',
                    id: 1,
                    name: 'SDS Molybdenum',
                    description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
                    date: '',
                    active: false,
                    selected: false,
                    disabled: false,
                    formattedDate: '',
                    showDetails: false,
                    tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
                    progress: 0,
                    walletFavorite: false,
                    walletDate: '',
                    formattedWalletDate: '',
                    launchbar: false,
                    menuActive: false,
                    details: 'More details about the item.',
        
                },
            ],
            open: false,
            shared: false,
            menuOpen: false,
            file: null,
            menuActive: false
        },
        // {
        //     name: "Service",
        //     type: "folder",
        //     folders: [
        // {
        //     name: "Standards",
        //     type: "folder",
        //     folders: [],
        //     files: [],
        //     open: false,
        //     shared: false,
        //     menuOpen: false,
        //     file: null,
        //     menuActive: false
        // },
        // {
        //     name: "Components",
        //     type: "folder",
        //     folders: [],
        //     files: [],
        //     open: false,
        //     shared: false,
        //     menuOpen: false,
        //     file: null,
        //     menuActive: false
        // }
        // ],

        //     files: [],
        //     open: false,
        //     shared: true,
        //     menuOpen: false,
        //     file: null,
        //     menuActive: false
        // },
        {
            name: "Reference",
            type: "folder",
            folders: [],
            files: [],
            open: false,
            shared: true,
            menuOpen: false,
            file: null,
            menuActive: false
        }
    ],
    files: [
        {
            category: 'Part',
            type: 'file',
            id: 1,
            name: 'EXH-SU-B3',
            description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
            date: '',
            active: false,
            selected: false,
            disabled: false,
            formattedDate: '',
            showDetails: false,
            tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
            progress: 0,
            walletFavorite: false,
            walletDate: '',
            formattedWalletDate: '',
            launchbar: false,
            menuActive: false,
            details: 'More details about the item.',

        },
        {
            category: 'Part',
            type: 'file',
            id: 1,
            name: 'WHFA-196',
            description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
            date: '',
            active: false,
            selected: false,
            disabled: false,
            formattedDate: '',
            showDetails: false,
            tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
            progress: 0,
            walletFavorite: false,
            walletDate: '',
            formattedWalletDate: '',
            launchbar: false,
            menuActive: false,
            details: 'More details about the item.',
        },
        {
            category: 'Part',
            type: 'file',
            id: 1,
            name: 'EXH-SU-B4',
            description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
            date: '',
            active: false,
            selected: false,
            disabled: false,
            formattedDate: '',
            showDetails: false,
            tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
            progress: 0,
            walletFavorite: false,
            walletDate: '',
            formattedWalletDate: '',
            launchbar: false,
            menuActive: false,
            details: 'More details about the item.',

        },
        {
            category: 'Part',
            type: 'file',
            id: 1,
            name: 'EXH-SU-B42',
            description: 'Description of the item. Details and metadata may go here, and well as other useful information. Year: 2019',
            date: '',
            active: false,
            selected: false,
            disabled: false,
            formattedDate: '',
            showDetails: false,
            tags: ['Tag', 'Part', 'Placeholder Tag', 'Placeholder Tag 1', 'Placeholder Tag 2', 'Tag', 'Document', 'Placeholder Tag 1', 'Placeholder Tag'],
            progress: 0,
            walletFavorite: false,
            walletDate: '',
            formattedWalletDate: '',
            launchbar: false,
            menuActive: false,
            details: 'More details about the item.',

        }
    ],
    open: false,
    shared: false,
    menuOpen: false,
    file: null,
    menuActive: false
}