import { IEntity } from '../models/entity.model';

export const walletItems: IEntity[] = [
    {
        category: 'item',
        type: 'file',
        name: 'Part',
        id: 1,
        description: '',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        details: '',
        progress: 0,
        tags: [],
        walletFavorite: false,
        walletDate: '',
        formattedWalletDate: '',
        launchbar: false,
        menuActive: false
    },
    {
        category: 'item',
        type: 'file',
        name: 'Requirement',
        id: 1,
        description: '',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        details: '',
        progress: 0,
        tags: [],
        walletFavorite: false,
        walletDate: '',
        formattedWalletDate: '',
        launchbar: false,
        menuActive: false
    },
    {
        category: 'item',
        type: 'file',
        name: 'Material',
        id: 1,
        description: '',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        details: '',
        progress: 0,
        tags: [],
        walletFavorite: false,
        walletDate: '',
        formattedWalletDate: '',
        launchbar: false,
        menuActive: false
    },
    {
        category: 'item',
        type: 'file',
        name: 'Document',
        id: 1,
        description: '',
        date: '',
        active: false,
        selected: false,
        disabled: false,
        formattedDate: '',
        showDetails: false,
        details: '',
        progress: 0,
        tags: [],
        walletFavorite: false,
        walletDate: '',
        formattedWalletDate: '',
        launchbar: false,
        menuActive: false
    },
    // {
    //   type: 'item',
    //   name: 'EXH',
    //   selected: false
    // },
    // {
    //   type: 'item',
    //   name: 'Stainless Steel',
    //   selected: false
    // }
];
